### ISSUE TITLE
网页自动填充

### ISSUE THREAD

**Issue by cethereal** [ftyszyx/lockpass#1]
功能请求（后面有意向添加下面两个功能吗）：
1. 像 1pass 那种 在已记录网站的登录页 账号密码输入框下面浮出所有账号 密码信息 点击可以自动填充 现在还要按快捷键 -> 关键字搜索才能填充
2. 新注册账号弹出是否保存记录

问题：
mac arm的 finder上 显示好大一块
系统版本：15.0 (24A335)
![052d274ff5a1f11a91452dea515a0aa7](https://github.com/user-attachments/assets/d6e927d3-3ee7-46dc-b4d7-b7780c25aabd)

**Comment by ftyszyx** [comment]
1.你说的是1pass的浏览器插件功能吧，我这个软件目前没有做浏览器插件，读不了浏览器的信息。
2、没看懂是什么意思
3、mac上显示好大一块，没明白。我没有mac电脑，的确没体验过。有机会去mac机上安装试试，到时处理一下

**Comment by ftyszyx** [comment]
因没有mac电脑，无法测试，先不发布mac版本了。问题先关闭
