### ISSUE TITLE
优化建议:左侧保险库是否可以添加一个滚动条

### ISSUE THREAD

**Issue by yomige** [ftyszyx/lockpass#4]
目前我的使用情形是：比如Github这个保险库，保险库里对应的保密项目是我的各个github账号。类似的情况包括，一台服务器是一个保险库，该保险库可能对应的保密项目是该服务器下部署的各个网站后台账号、各个网站对应的数据库账号密码。

如果保险库很多的时候，能否在左侧的保险库也增加一个滚动条。

![image](https://github.com/user-attachments/assets/19ce2275-9299-4386-a0b1-d3c5c15f4326)

**Comment by ftyszyx** [comment]
![image](https://github.com/user-attachments/assets/adda2307-2e54-4cd1-bc9a-d25fd7182070)
