### ISSUE TITLE
bug:密码管理器的排序功能是不是不好用

### ISSUE THREAD

**Issue by xgit01** [ftyszyx/lockpass#5]
如题：
![图片](https://github.com/user-attachments/assets/80d1a243-5f82-4ba8-9a81-0788ca681bed)

**Comment by ftyszyx** [comment]
![image](https://github.com/user-attachments/assets/5eeb763d-770a-44ff-89de-e9f8b5faa757)
是这个吗，漏了，有空会加上时间排序

**Comment by ftyszyx** [comment]
可以修改排序了
